server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/spring_learn"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 170804
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 36000 # in seconds
  refreshable-duration: 360000 # in seconds
app:
  services:
    profile: http://localhost:8081/profile